//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClothingStore.OrdersService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CheckoutProcessorSoap", Namespace="http://tempuri.org/")]
    public partial class CheckoutProcessor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StoringOperationCompleted;
        
        private System.Threading.SendOrPostCallback TotalCaluatorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CheckoutProcessor() {
            this.Url = global::ClothingStore.Properties.Settings.Default.ClothingStore_OrdersService_CheckoutProcessor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StoringCompletedEventHandler StoringCompleted;
        
        /// <remarks/>
        public event TotalCaluatorCompletedEventHandler TotalCaluatorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Storing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Storing(Order currentOrder) {
            object[] results = this.Invoke("Storing", new object[] {
                        currentOrder});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StoringAsync(Order currentOrder) {
            this.StoringAsync(currentOrder, null);
        }
        
        /// <remarks/>
        public void StoringAsync(Order currentOrder, object userState) {
            if ((this.StoringOperationCompleted == null)) {
                this.StoringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoringOperationCompleted);
            }
            this.InvokeAsync("Storing", new object[] {
                        currentOrder}, this.StoringOperationCompleted, userState);
        }
        
        private void OnStoringOperationCompleted(object arg) {
            if ((this.StoringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoringCompleted(this, new StoringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TotalCaluator", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal TotalCaluator(decimal discountPrecent, decimal price, int quantity) {
            object[] results = this.Invoke("TotalCaluator", new object[] {
                        discountPrecent,
                        price,
                        quantity});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void TotalCaluatorAsync(decimal discountPrecent, decimal price, int quantity) {
            this.TotalCaluatorAsync(discountPrecent, price, quantity, null);
        }
        
        /// <remarks/>
        public void TotalCaluatorAsync(decimal discountPrecent, decimal price, int quantity, object userState) {
            if ((this.TotalCaluatorOperationCompleted == null)) {
                this.TotalCaluatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTotalCaluatorOperationCompleted);
            }
            this.InvokeAsync("TotalCaluator", new object[] {
                        discountPrecent,
                        price,
                        quantity}, this.TotalCaluatorOperationCompleted, userState);
        }
        
        private void OnTotalCaluatorOperationCompleted(object arg) {
            if ((this.TotalCaluatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TotalCaluatorCompleted(this, new TotalCaluatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Order {
        
        private decimal orderTotalField;
        
        private System.DateTime orderDateField;
        
        private int refundRequestedField;
        
        private int userIDField;
        
        private byte[] orderItemsField;
        
        /// <remarks/>
        public decimal orderTotal {
            get {
                return this.orderTotalField;
            }
            set {
                this.orderTotalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime orderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public int refundRequested {
            get {
                return this.refundRequestedField;
            }
            set {
                this.refundRequestedField = value;
            }
        }
        
        /// <remarks/>
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] orderItems {
            get {
                return this.orderItemsField;
            }
            set {
                this.orderItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void StoringCompletedEventHandler(object sender, StoringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StoringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StoringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TotalCaluatorCompletedEventHandler(object sender, TotalCaluatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TotalCaluatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TotalCaluatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591